[package]
name = "udp_polygon"
version = "0.1.0"
edition = "2021"
readme = "README.md"


[lib]
name = "udp_polygon"
path = "./src/lib.rs"

[dependencies]
toml = "0.7"
serde = "1.0"
serde_derive = "1.0"

